schema_version = "1.0"

[task]
name = "swemera/go-004"
keywords = ["go", "issue-resolving", "goccy/go-yaml"]

[metadata]
difficulty = "hard"
difficulty_score = 0.735
category = "software-development"
language = "go"
repo = "goccy/go-yaml"
instance_id = "goccy__go-yaml-862"
base_commit = "d4021ff736c7fea2f9b40de179e80205ce52051c"

[verifier]
network_mode = "public"
timeout_sec = 3600

[agent]
network_mode = "public"
timeout_sec = 3600

[environment]
build_timeout_sec = 3600
cpus = 2
memory_mb = 4096
storage_mb = 16384
gpus = 0
