schema_version = "1.0"

[task]
name = "swemera/go-018"
keywords = ["go", "issue-resolving", "osteele/liquid"]

[metadata]
difficulty = "hard"
difficulty_score = 0.725
category = "software-development"
language = "go"
repo = "osteele/liquid"
instance_id = "osteele__liquid-137"
base_commit = "c070a555714da9da606caededc33511f041ac808"

[verifier]
network_mode = "public"
timeout_sec = 3600

[agent]
network_mode = "public"
timeout_sec = 3600

[environment]
build_timeout_sec = 3600
cpus = 2
memory_mb = 4096
storage_mb = 16384
gpus = 0
